#!/usr/bin/env node
'use strict';

const child_process = require('child_process');
const fs = require('fs');
const path = require('path');

// Make sure we're Node 6+

try {
	eval('{ let [a] = [1]; }');
} catch (e) {
	console.log("We require Node.js v6 or later; you're using " + process.version);
	process.exit();
}

// Make sure our dependencies are available, and install them if they
// aren't

try {
	require.resolve('sockjs');
} catch (e) {
	console.log('Installing dependencies...');
	child_process.execSync('npm install --production', {stdio: 'inherit'});
}

// Check if the server is configured to use Go, and ensure the required
// environment variables and dependencies are available if that is the case

let config;
try {
	config = require('./config/config');
} catch (e) {}

if (config && config.golang) {
	if (!process.env.GOPATH) {
		console.log('The GOPATH environment variable is not set! It is required in order to run the server using Go.');
		process.exit(0);
	}
	if (!process.env.GOROOT) {
		console.log('The GOROOT environment variable is not set! It is required in order to run the server using Go.');
		process.exit(0);
	}

	const dependencies = ['github.com/gorilla/mux', 'github.com/igm/sockjs-go/sockjs'];
	let packages = child_process.execSync('go list all', {stdio: null, encoding: 'utf8'});
	for (let dep of dependencies) {
		if (!packages.includes(dep)) {
			console.log(`Dependency ${dep} is not installed. Fetching...`);
			child_process.execSync(`go get ${dep}`, {stdio: 'inherit'});
		}
	}

	const {GOPATH} = process.env;
	let stat;
	let needsSrcDir = false;
	try {
		stat = fs.lstatSync(path.resolve(GOPATH, 'src/github.com/Zarel'));
	} catch (e) {
		needsSrcDir = true;
	} finally {
		if (stat && !stat.isDirectory()) {
			needsSrcDir = true;
		}
	}

	let srcPath = path.resolve(__dirname, 'sockets');
	let tarPath = path.resolve(GOPATH, 'src/github.com/Zarel/Pokemon-Showdown/sockets');
	if (needsSrcDir) {
		try {
			fs.mkdirSync(path.resolve(GOPATH, 'src/github.com/Zarel'));
			fs.mkdirSync(path.resolve(GOPATH, 'src/github.com/Zarel/Pokemon-Showdown'));
		} catch (e) {
			console.log(e);
			console.error(`Cannot make go source directory for the sockets library files! Symlink them manually from ${srcPath} to ${tarPath}`);
			process.exit(0);
		}
	}

	try {
		stat = fs.lstatSync(path.resolve(GOPATH, 'src/github.com/Zarel/Pokemon-Showdown/sockets'));
	} catch (e) {}

	if (!stat || !stat.isSymbolicLink()) {
		try {
			if (process.platform === 'win32') {
				child_process.execSync(`mklink /J ${tarPath} ${srcPath}`, {stdio: 'inherit'});
			} else {
				child_process.execSync(`ln -sF ${srcPath} ${tarPath}`, {stdio: 'inherit'});
			}
		} catch (e) {
			console.error(`Cannot make go source directory for the sockets library files! Symlink them manually from ${srcPath} to ${tarPath}`);
			process.exit(0);
		}
	}

	console.log('Building Go source libs...');
	try {
		child_process.execSync('go install github.com/Zarel/Pokemon-Showdown/sockets', {stdio: 'inherit'});
	} catch (e) {
		process.exit(0);
	}
}

// Start the server. We manually load app.js so it can be configured to run as
// the main module, rather than this file being considered the main module.
// This ensures any dependencies that were just installed can be found when
// running on Windows and avoids any other potential side effects of the main
// module not being app.js like it is assumed to be.
//
// The port the server should host on can be passed using the second argument
// when launching with this file the same way app.js normally allows, e.g. to
// host on port 9000:
// $ ./pokemon-showdown 9000

require('module')._load('./app', module, true);
